grade-atk_local:
  when: manual
  timeout: 1 minute 15 seconds
  script:
    - /bin/bash --login isl-grade atk local 
  coverage: '/Score: .*\((\d+)%\)/'
  interruptible: false

grade-atk_remote:
  when: manual
  timeout: 1 minute 30 seconds
  script:
    - /bin/bash --login isl-grade atk remote 
  coverage: '/Score: .*\((\d+)%\)/'
  interruptible: false

grade-def1:
  when: manual
  timeout: 2 minute
  script:
    - /bin/bash --login isl-grade def 1
  coverage: '/Score: .*\((\d+)%\)/'
  interruptible: false

grade-def2:
  when: manual
  timeout: 2 minute
  script:
    - /bin/bash --login isl-grade def 2
  coverage: '/Score: .*\((\d+)%\)/'
  interruptible: false

grade-def3:
  when: manual
  timeout: 2 minute
  script:
    - /bin/bash --login isl-grade def 3
  coverage: '/Score: .*\((\d+)%\)/'
  interruptible: false

after_script:
  - /bin/bash grader-cleanup
